In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
import shutil
import re
import seaborn as sns

In [61]:
#Define cell parameters
cell_dm_bohr = 19.3217899560
cell_dm_ang = cell_dm_bohr * 0.529177
cell_matrix = np.array([1.00000000000,  0.000000000000,  0.00000000000,
                          -0.500000000000,  0.866025403784,  0.000000000000, 
                          0.000000000000,  0.000000000000,  2.283539330750]).reshape(3,3)
cell_matrix = cell_matrix * cell_dm_ang

#multiplied cell parameters
cell_dm_bohr = 19.3217899560
cell_dm_ang = cell_dm_bohr * 0.529177
cell_matrix_mult = np.array([1.00000000000*2,  0.000000000000,  0.00000000000,
                          -0.500000000000*2,  0.866025403784*2,  0.000000000000, 
                          0.000000000000,  0.000000000000,  2.283539330750]).reshape(3,3)
cell_matrix_mult = cell_matrix_mult * cell_dm_ang

In [62]:
cell_matrix_mult

array([[ 20.44929369,   0.        ,   0.        ],
       [-10.22464684,  17.70960782,   0.        ],
       [  0.        ,   0.        ,  23.34838321]])

In [4]:
def qsline_to_coordinate(coord_line, cell_matrix):
    coord_list = coord_line.split()[1:4]
    atom_type = coord_line.split()[0]
    for n in range(len(coord_list)):
        coord_list[n] = re.sub("d","0",coord_list[n])
        coord_list[n] = float(coord_list[n])
    coord_array = np.array(coord_list).reshape(1,3)
    coord_array_ang = np.dot(coord_array,cell_matrix)
    return (atom_type,coord_array_ang)

In [6]:
main_dir = './'
bader_df = pd.read_csv('./1_Ag_subCu/charge_df.csv')
coordinate_df = open('./1_Ag_subCu/input.in','r')
coord_lines = coordinate_df.readlines()

In [16]:
bader_df

,Unnamed: 0,atom_type,x,y,z,Charge,Min_dist,atomic_volume,surface_atom,bader_charge
0,0,Cu,-0.0072,0.0257,4.1772,19.0306,2.0714,382.5950,0,-0.0306
1,1,Ni,4.7832,0.0495,4.2919,18.0640,2.0447,307.6178,0,-0.0640
2,2,Cu,-0.0051,16.7322,4.1097,19.0190,2.1071,409.7094,0,-0.0190
3,3,Cu,14.4615,0.0492,4.0996,19.0120,2.1051,417.7300,0,-0.0120
4,4,Ni,16.8115,4.3120,4.2676,18.0450,2.0133,345.6806,0,-0.0450
...,...,...,...,...,...,...,...,...,...,...
59,59,Cu,9.6306,8.3510,15.5927,18.9951,2.0929,424.3526,1,0.0049
60,60,Cu,-7.2277,12.5502,15.5512,19.0248,2.0737,389.9148,1,-0.0248
61,61,Ni,-2.2883,12.6139,15.3984,18.0358,1.9919,317.1977,1,-0.0358
62,62,Ni,2.3849,12.3606,15.3958,18.0354,2.0488,282.9653,1,-0.0354
63,63,Ni,7.2669,12.3992,15.4074,18.0272,1.9989,274.0349,1,-0.0272

In [42]:
cell_x = cell_matrix[0]
cell_y = cell_matrix[1]
cell_z = cell_matrix[2]
cell_xy = cell_x + cell_y

cellx_bader = bader_df.copy()
cellx_bader['x'] = cellx_bader['x'] + cell_x[0]
cellx_bader

celly_bader = bader_df.copy()
celly_bader['x'] = celly_bader['x'] + cell_y[0]
celly_bader['y'] = celly_bader['y'] + cell_y[1]
celly_bader

cellxy_bader = bader_df.copy()
cellxy_bader['x'] = cellxy_bader['x'] + cell_xy[0]
cellxy_bader['y'] = cellxy_bader['y'] + cell_xy[1]
cellxy_bader

cell_original = bader_df.copy()

repeated_bader_df = pd.concat([cell_original, cellx_bader, celly_bader, cellxy_bader],ignore_index=True)

In [43]:
repeated_bader_df

,Unnamed: 0,atom_type,x,y,z,Charge,Min_dist,atomic_volume,surface_atom,bader_charge
0,0,Cu,-0.007200,0.025700,4.1772,19.0306,2.0714,382.5950,0,-0.0306
1,1,Ni,4.783200,0.049500,4.2919,18.0640,2.0447,307.6178,0,-0.0640
2,2,Cu,-0.005100,16.732200,4.1097,19.0190,2.1071,409.7094,0,-0.0190
3,3,Cu,14.461500,0.049200,4.0996,19.0120,2.1051,417.7300,0,-0.0120
4,4,Ni,16.811500,4.312000,4.2676,18.0450,2.0133,345.6806,0,-0.0450
...,...,...,...,...,...,...,...,...,...,...
251,59,Cu,14.742923,17.205804,15.5927,18.9951,2.0929,424.3526,1,0.0049
252,60,Cu,-2.115377,21.405004,15.5512,19.0248,2.0737,389.9148,1,-0.0248
253,61,Ni,2.824023,21.468704,15.3984,18.0358,1.9919,317.1977,1,-0.0358
254,62,Ni,7.497223,21.215404,15.3958,18.0354,2.0488,282.9653,1,-0.0354
255,63,Ni,12.379223,21.254004,15.4074,18.0272,1.9989,274.0349,1,-0.0272

In [78]:
mult_coord_file = open('./1_Ag_subCu/mult_coord.in','w')
for i in range(0,len(repeated_bader_df)):
    atom_type = repeated_bader_df.atom_type[i]
    coord = np.array([repeated_bader_df.x[i], repeated_bader_df.y[i], repeated_bader_df.z[i]])
    fract_pos_atom = np.linalg.lstsq(cell_matrix_mult.T,coord.T,rcond=None)
    fract_pos_atom = fract_pos_atom[0]/2
    line = atom_type + '      ' 
    for i in fract_pos_atom:
        line = line + str(i) + '      '
    mult_coord_file.write(line + '\n')
mult_coord_file.close()

In [65]:
pos_atom[0]/2

array([0.00018675, 0.00072559, 0.08945373])

In [51]:
np.matmul([0.0003984294,0.0015372176,0.0946746194],cell_matrix)

array([-0.00378495,  0.01361176,  2.21049929])

In [59]:
print(0.0003984294*2)
print(0.0015372176*2)
print(0.0946746194*2)

0.0007968588
0.0030744352
0.1893492388

In [52]:
coord_lines

['Cu            0.0003984294        0.0015372176        0.0946746194\n',
 'Ni            0.2490339313        0.0029574044        0.0972739505\n',
 'Cu            0.4997073835       -0.0000560392        0.0931433438\n',
 'Cu            0.7499240576        0.0029395687        0.0929141542\n',
 'Ni           -0.0010745390        0.2576915899        0.0967224662\n',
 'Cu            0.2473868979        0.2506653091        0.0948729914\n',
 'Cu            0.5028069548        0.2502669540        0.0937334992\n',
 'Ni            0.7569423728        0.2576424405        0.0972772305\n',
 'Ni           -0.0014652502        0.4963392810        0.0969301587\n',
 'Ni            0.2455246955        0.5024518906        0.0968974449\n',
 'Cu            0.5003371355        0.5018105510        0.0944893670\n',
 'Ni            0.7518635062        0.4963212695        0.0979894200\n',
 'Cu           -0.0006628994        0.7484248852        0.0939367266\n',
 'Cu            0.2481451058        0.7488714384        0.0932956126\n',
 'Ni            0.4963355261        0.7479645863        0.0957171200\n',
 'Cu            0.7486480985        0.7475937477        0.0942979593\n',
 'Ni            0.1656454339        0.0796836449        0.1816199316\n',
 'Cu            0.4175124872        0.0837897883        0.1804810909\n',
 'Cu            0.6679665549        0.0863301073        0.1807243370\n',
 'Cu            0.9184817857        0.0845347789        0.1806835481\n',
 'Cu            0.1658915839        0.3318498717        0.1812599964\n',
 'Cu            0.4188601528        0.3321858620        0.1805259764\n',
 'Ni            0.6694944896        0.3351414181        0.1811868293\n',
 'Ni            0.9183131096        0.3355494382        0.1806930101\n',
 'Ni            0.1640774160        0.5798813259        0.1811608048\n',
 'Cu            0.4162278106        0.5833818010        0.1803129900\n',
 'Ni            0.6718599491        0.5808466180        0.1809466316\n',
 'Cu            0.9194866862        0.5848125238        0.1817702143\n',
 'Cu            0.1664189936        0.8322706113        0.1803270092\n',
 'Cu            0.4148422899        0.8317053541        0.1802030198\n',
 'Cu            0.6677226919        0.8329704952        0.1794127604\n',
 'Ni            0.9172759395        0.8312965850        0.1809616283\n',
 'Ni            0.0870122979        0.1662466955        0.2668795548\n',
 'Ni            0.3302308659        0.1630307787        0.2663003296\n',
 'Ni            0.5795014330        0.1685660283        0.2663509621\n',
 'Cu            0.8350137943        0.1700036909        0.2672331081\n',
 'Ni            0.0849368282        0.4197362588        0.2658438040\n',
 'Cu            0.3333224606        0.4165806886        0.2660108559\n',
 'Ni            0.5845736146        0.4158516765        0.2660598683\n',
 'Cu            0.8345880951        0.4184898918        0.2667985572\n',
 'Ni            0.0876474558        0.6695681504        0.2667245657\n',
 'Ni            0.3269862528        0.6660081951        0.2660176738\n',
 'Cu            0.5831673058        0.6650505639        0.2647631400\n',
 'Ni            0.8352205002        0.6689394437        0.2662463769\n',
 'Ni            0.0838515708        0.9167029865        0.2655408988\n',
 'Ni            0.3301558216        0.9171961205        0.2668172018\n',
 'Cu            0.5803622999        0.9167392360        0.2662636458\n',
 'Cu            0.8348085741        0.9171236363        0.2661369498\n',
 'Ni            0.0076871539        0.0010752997        0.3490839600\n',
 'Cu            0.2495259348       -0.0007578257        0.3538180659\n',
 'Ni            0.4931944243        0.0036549494        0.3494056215\n',
 'Ag            0.7479330852       -0.0026038220        0.3643360326\n',
 'Cu            0.0071141034        0.2543248771        0.3522618494\n',
 'Ni            0.2539653519        0.2483025719        0.3496685720\n',
 'Ni            0.4970499975        0.2508100657        0.3486412615\n',
 'Ni            0.7376143311        0.2497336670        0.3501346762\n',
 'Cu            0.0006203889        0.5001424738        0.3525431152\n',
 'Cu            0.2522515058        0.4991169006        0.3528626333\n',
 'Ni            0.5009763113        0.4981155585        0.3501304020\n',
 'Cu            0.7479666965        0.4990693585        0.3534001255\n',
 'Cu            0.0009392933        0.7500192024        0.3524574385\n',
 'Ni            0.2584823326        0.7538238126        0.3489949945\n',
 'Ni            0.4927755086        0.7386889577        0.3489370092\n',
 'Ni            0.7465956368        0.7409975939        0.3492003265\n']

In [79]:
cell_dm_bohr = 19.3217899560
cell_dm_ang = cell_dm_bohr * 0.529177
cell_matrix_mult = np.array([1.00000000000*2,  0.000000000000,  0.00000000000,
                          -0.500000000000*2,  0.866025403784*2,  0.000000000000, 
                          0.000000000000,  0.000000000000,  2.283539330750]).reshape(3,3)

In [80]:
cell_matrix_mult

array([[ 2.        ,  0.        ,  0.        ],
       [-1.        ,  1.73205081,  0.        ],
       [ 0.        ,  0.        ,  2.28353933]])